[package]
name = "housekeeper"
version = "0.3.1"
edition = "2018"
license = "GPL-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
infer = "0.5.0"
src = "0.0.6"
